apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: onlineshop.com
      http:
        paths:
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: userservice-clusterip-srv   
                port:
                  number: 8080
          - path: /api/c/shoppingcarts
            pathType: Prefix
            backend:
              service:
                name: shoppingcartservice-clusterip-srv
                port:
                  number: 8080
          - path: /api/c/itemsshoppingcart
            pathType: Prefix
            backend:
              service:
                name: shoppingcartservice-clusterip-srv
                port:
                  number: 8080
          - path: /api/products
            pathType: Prefix
            backend:
              service:
                name: productservice-clusterip-srv
                port:
                  number: 8080
          - path: /api/suppliers
            pathType: Prefix
            backend:
              service:
                name: productservice-clusterip-srv
                port:
                  number: 8080
          - path: /api/supplierproductorders
            pathType: Prefix
            backend:
              service:
                name: productservice-clusterip-srv
                port:
                  number: 8080
          - path: /api/productratings
            pathType: Prefix
            backend:
              service:
                name: productservice-clusterip-srv
                port:
                  number: 8080
          - path: /api/productcategories
            pathType: Prefix
            backend:
              service:
                name: productservice-clusterip-srv
                port:
                  number: 8080
